name: Upload to App Distribution
description: Automates the process of uploading an Android build to Google Play Console, including generating required secret files, setting up dependencies, and executing Fastlane for deployment.
inputs:
  env:
    required: true
    description: Environmental variable specifying the build environment (e.g., development, production).
  version:
    required: true
    description: The version of the app to be uploaded.
  build_number:
    required: true
    description: The build number for the app version.

runs:
  using: "composite"
  steps:
    - name: Generate secret files
      shell: bash
      run: |
        make ${{ inputs.env }}

    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        distribution: microsoft
        java-version: 17

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3.5"

    - name: Install Flutter
      shell: bash
      run: |
        git clone https://github.com/flutter/flutter.git
        cd flutter
        git checkout 3.32.3
        cd ..

    - name: Add path
      shell: bash
      run: echo "$(pwd)/flutter/bin" >> $GITHUB_PATH

    - name: Download Flutter packages
      shell: bash
      run: dart pub global activate flutterfire_cli

    - name: Upload App Distribution
      shell: bash
      run: |
        cd android
        bundle install
        bundle exec fastlane upload_firebase_distribution env:${{inputs.env}} version:${{inputs.version}} build_number:${{inputs.build_number}}
