name: koshiba_agent_app
description: "小柴エージェントアプリ"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  shimmer: ^3.0.0
  dio: ^5.8.0+1
  flutter_svg: ^2.0.17
  reactive_forms: ^17.0.1
  reactive_forms_annotations: ^6.0.0
  flutter_secure_storage: ^9.2.4
  gap: ^3.0.1
  riverpod: ^2.6.1
  logger: ^2.5.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  page_transition: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  go_router_builder: ^2.8.2
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9
  reactive_forms_generator: ^6.1.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  dartdoc: ^8.3.3

flutter_launcher_icons:
  android: true
  image_path_android: "assets/images/app_icon.png"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  ios: true
  image_path_ios:  "assets/images/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  fullscreen: true
  web: false
  android: true
  ios: true
  ios_content_mode: scaleAspectFill
  image: "assets/images/app_icon.png"
  android_12:
    icon_background_color: '#FFFFFF'
    image: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   
flutter_intl:
  enabled: true
