name: koshiba_agent_app
description: "小柴エージェントアプリ"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  cloud_firestore: ^5.6.6
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  extension_google_sign_in_as_googleapis_auth: ^2.0.13
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  go_router: ^14.8.1
  google_sign_in: ^6.3.0
  googleapis: ^14.0.0
  hooks_riverpod: ^2.6.1
  http: ^1.4.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  page_transition: ^2.2.1
  reactive_date_time_picker: ^5.0.0
  reactive_forms: ^17.0.1
  reactive_forms_annotations: ^6.0.0
  retrofit: ^4.4.2
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  string_validator: ^1.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  dartdoc: ^8.3.3
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  go_router_builder: ^2.8.2
  intl_utils: ^2.8.10
  json_serializable: ^6.9.4
  reactive_forms_generator: ^6.1.1
  retrofit_generator: ^9.1.9
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter_launcher_icons:
  android: true
  image_path_android: "assets/images/app_icon.png"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  ios: true
  image_path_ios: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  fullscreen: true
  web: false
  android: true
  ios: true
  ios_content_mode: scaleAspectFill
  image: "assets/images/app_icon.png"
  android_12:
    icon_background_color: "#FFFFFF"
    image: "assets/images/app_icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true
  class_name: AppMessage
  main_locale: ja
