// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEoBVgO3UpDti6WcNS2f3KURsVL3Ax-4k',
    appId: '1:545963589750:web:b670bd0d65542f7bac1f57',
    messagingSenderId: '545963589750',
    projectId: 'koshiba-agent-bcc2e',
    authDomain: 'koshiba-agent-bcc2e.firebaseapp.com',
    storageBucket: 'koshiba-agent-bcc2e.firebasestorage.app',
    measurementId: 'G-C9PCYJ1ENR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxwfC0RejHcM9Rj3cEdzqpLsfUTVAGU7k',
    appId: '1:545963589750:android:e38bb3abfab5aa7cac1f57',
    messagingSenderId: '545963589750',
    projectId: 'koshiba-agent-bcc2e',
    storageBucket: 'koshiba-agent-bcc2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMubNoXWkczsWaYLgyxanUqkKVvA7b8yc',
    appId: '1:545963589750:ios:3336d6aa6f8e868eac1f57',
    messagingSenderId: '545963589750',
    projectId: 'koshiba-agent-bcc2e',
    storageBucket: 'koshiba-agent-bcc2e.firebasestorage.app',
    androidClientId:
        '545963589750-7jc43o556qnq6bqs98otk6nr189q03dp.apps.googleusercontent.com',
    iosClientId:
        '545963589750-pemaqig735o8lbtceu92t8f8nnlg1doq.apps.googleusercontent.com',
    iosBundleId: 'jp.co.koshiba.agent.dev',
  );
}
