name: "[Prd] Upload to TestFlight, AppDistribution and Firebase Hosting"

on:
  push:
    tags:
      - 'v*'

jobs:
  upload_prd_app_distribution:
    name: "[Prd] Upload to AppDistribution"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout triggered branch
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT_TOKEN }}
      - name: Extract version and build number from tag
        id: extract_version_android
        run: |
          TAG_NAME=${GITHUB_REF_NAME}
          VERSION=$(echo $TAG_NAME | sed 's/^v\([0-9]*\.[0-9]*\.[0-9]*\).*/\1/')
          BUILD_NUMBER=$(echo $TAG_NAME | sed 's/^v[0-9]*\.[0-9]*\.[0-9]*+\([0-9]*\)/\1/')
          if [ -z "$BUILD_NUMBER" ]; then
            BUILD_NUMBER=1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT
      - name: Upload to AppDistribution
        uses: ./.github/workflows/upload_android
        with:
          env: prd
          version: ${{ steps.extract_version_android.outputs.version }}
          build_number: ${{ steps.extract_version_android.outputs.build_number }}
  upload_prd_app_store:
    name: "[Prd] Upload to TestFlight"
    runs-on: macos-latest
    steps:
      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app
      - name: Checkout triggered branch
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT_TOKEN }}
      - name: Extract version and build number from tag
        id: extract_version_ios
        run: |
          TAG_NAME=${GITHUB_REF_NAME}
          VERSION=$(echo $TAG_NAME | sed 's/^v\([0-9]*\.[0-9]*\.[0-9]*\).*/\1/')
          BUILD_NUMBER=$(echo $TAG_NAME | sed 's/^v[0-9]*\.[0-9]*\.[0-9]*+\([0-9]*\)/\1/')
          if [ -z "$BUILD_NUMBER" ]; then
            BUILD_NUMBER=1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT
      - name: Upload to TestFlight
        uses: ./.github/workflows/upload_ios
        with:
          env: prd
          version: ${{ steps.extract_version_ios.outputs.version }}
          build_number: ${{ steps.extract_version_ios.outputs.build_number }}
          fastlane_user: ${{ secrets.FASTLANE_USER }}
          fastlane_apple_application_specific_password: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
  upload_prd_web:
    name: "[Prd] Deploy to Firebase Hosting"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout triggered branch
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT_TOKEN }}
      - name: Deploy to Firebase Hosting
        uses: ./.github/workflows/upload_web
        with:
          env: prd
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          firebase_service_account: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KOSHIBA_AGENT_BCC2E }}'
          channel_id: live
          project_id: koshiba-agent-bcc2e
